try latest mingw
The MingW64 issue
https://sourceforge.net/p/mingw-w64/bugs/850/#d4b6 
causing ICD to not build is caused by a duplicate key.
So, comment that  out in our ICD code.

In file included from /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/include/devpkey.h:19,
                 from loader/windows/icd_windows_hkr.c:27:
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/include/devpkey.h:28:1: error: conflicting types for 'DEVPKEY_Device_ClassGuid'
   28 | DEFINE_DEVPROPKEY(DEVPKEY_Device_ClassGuid, 0xa45c254e,0xdf1c,0x4efd,0x80,0x20,0x67,0xd1,0x46,0xa8,0x50,0xe0, 10);
      | ^~~~~~~~~~~~~~~~~
In file included from loader/windows/icd_windows_hkr.c:20:
loader/windows/icd_windows_hkr.h:40:19: note: previous definition of 'DEVPKEY_Device_ClassGuid' was here
   40 | DEFINE_DEVPROPKEY(DEVPKEY_Device_ClassGuid,              0xa45c254e, 0xdf1c, 0x4efd, 0x80, 0x20, 0x67, 0xd1, 0x46, 0xa8, 0x50, 0xe0, 10);    // DEVPROP_TYPE_GUID