fix libsnappy which broke with a new commit
```
[16:56:57][DEBUG] Running 'ninja -j 4 ' in '/home/u/Desktop/_working/workdir/x86_64/snappy_git'
[1/5] Building CXX object CMakeFiles/snappy.dir/snappy-sinksource.cc.obj
[2/5] Building CXX object CMakeFiles/snappy.dir/snappy-c.cc.obj
[3/5] Building CXX object CMakeFiles/snappy.dir/snappy.cc.obj
FAILED: CMakeFiles/snappy.dir/snappy.cc.obj 
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/bin/x86_64-w64-mingw32-g++ --sysroot=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32  -DHAVE_CONFIG_H -I. -O3  -fstack-protector-all  -D_FORTIFY_SOURCE=2 -O3 -DNDEBUG   -std=c++11 -MD -MT CMakeFiles/snappy.dir/snappy.cc.obj -MF CMakeFiles/snappy.dir/snappy.cc.obj.d -o CMakeFiles/snappy.dir/snappy.cc.obj -c snappy.cc
snappy.cc:1359:3: error: 'ABSL_ATTRIBUTE_ALWAYS_INLINE' does not name a type
 1359 |   ABSL_ATTRIBUTE_ALWAYS_INLINE
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
snappy.cc: In member function 'bool snappy::SnappyScatteredWriter<Allocator>::AppendFromSelf(size_t, size_t, char**)':
snappy.cc:1586:10: error: 'memmove' is not a member of 'std'; did you mean 'remove'?
 1586 |     std::memmove(op, op - offset, kSlopBytes);
      |          ^~~~~~~
      |          remove
snappy.cc: In instantiation of 'void snappy::SnappyDecompressor::DecompressAllTags(Writer*) [with Writer = snappy::SnappyArrayWriter]':
snappy.cc:1024:3:   required from 'bool snappy::InternalUncompressAllTags(snappy::SnappyDecompressor*, Writer*, snappy::uint32, snappy::uint32) [with Writer = snappy::SnappyArrayWriter; snappy::uint32 = unsigned int]'
snappy.cc:1730:77:   required from here
snappy.cc:918:24: error: 'class snappy::SnappyArrayWriter' has no member named 'AppendFromSelf'
  918 |           if (!writer->AppendFromSelf(copy_offset, length, &op)) goto exit;
      |                ~~~~~~~~^~~~~~~~~~~~~~
snappy.cc:929:24: error: 'class snappy::SnappyArrayWriter' has no member named 'AppendFromSelf'
  929 |           if (!writer->AppendFromSelf(copy_offset, length, &op)) goto exit;
      |                ~~~~~~~~^~~~~~~~~~~~~~
[4/5] Building CXX object CMakeFiles/snappy.dir/snappy-stubs-internal.cc.obj
ninja: build stopped: subcommand failed.
[16:56:57][ERROR] Error [1] running pro
```