Add files via upload
Deadsix27's cmake version wouldn't build for me !   No idea why.
    error: 'ALIGNMENTA' undeclared (first use in this function); did you mean 'ALIGNEDA'?
    error: 'ALIGNMENT' undeclared (first use in this function); did you mean 'ALIGNED'?

So, have reverted to my known good build using old make,

And added fftw3_dll.py (etc) so that when we build this dependency, it build relevant DLLs (only) which can be distributed into and used by other windows apps on the PC.